server:
  port: 8081
spring:
  datasource:
    mysql:
      url: jdbc:mysql://doc-test:3306/sql-kafka
      username: root
      password: MySQLP@%%W)RD
      driver-class-name: com.mysql.cj.jdbc.Driver
#    mssql:
#      url: jdbc:sqlserver://DOCPROD\SQLPROD:1433;databaseName=GAZ;encrypt=false
#      username: DVSQL
#      password: DV_Cthdbc14@
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none # глобальная настройка
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect # глобальная настройка
